[package]
name = "ariadusage-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[[bin]]
name = "ariadusage"
path = "src/main.rs"

[dependencies]
ariadusage-core = { version = "0.0.0", path = "../ariadusage-core" }
ariadusage-engine = { version = "0.0.0", path = "../ariadusage-engine" }
ariadusage-protocol = { version = "0.0.0", path = "../ariadusage-protocol" }
clap = { workspace = true }
rpassword = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
tokio = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
