[package]
name = "ariadusage-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[[bin]]
name = "ariadusage-test-child"
path = "src/bin/ariadusage-test-child.rs"
required-features = ["test-hooks"]

[features]
default = []
test-hooks = ["dep:nix"]

[dependencies]
ariadusage-core = { version = "0.0.0", path = "../ariadusage-core" }
ariadusage-protocol = { version = "0.0.0", path = "../ariadusage-protocol" }
bytes = { workspace = true }
etcetera = { workspace = true }
reqwest = { workspace = true }
rustls = { workspace = true }
rustls-platform-verifier = { workspace = true }
serde = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true, features = ["codec"] }
zeroize = { workspace = true }
serde_json = { workspace = true }

[target.'cfg(unix)'.dependencies]
rustix = { workspace = true, features = ["fs", "process", "pipe"] }


[target.'cfg(target_os = "linux")'.dependencies]
process-wrap = { workspace = true }
procfs = { workspace = true }
nix = { workspace = true, optional = true }
pty-process = { workspace = true, features = ["async"] }

[dev-dependencies]
ariadusage-engine = { path = ".", features = ["test-hooks"] }
httpmock = { workspace = true }

[lints]
workspace = true
